idx_to_name = ['apple_pie'
,'baby_back_ribs'
,'baklava'
,'beef_carpaccio'
,'beef_tartare'
,'beet_salad'
,'beignets'
,'bibimbap'
,'bossam'
,'bread_pudding'
,'breakfast_burrito'
,'bruschetta'
,'bulgogi'
,'caesar_salad'
,'cannoli'
,'caprese_salad'
,'carrot_cake'
,'ceviche'
,'cheese_plate'
,'cheesecake'
,'chicken_curry'
,'chicken_quesadilla'
,'chicken_wings'
,'chocolate_cake'
,'chocolate_mousse'
,'churros'
,'clam_chowder'
,'club_sandwich'
,'crab_cakes'
,'creme_brulee'
,'croque_madame'
,'cup_cakes'
,'daegaejjim'
,'dakbokkeumtang'
,'deviled_eggs'
,'doenjang_chigae'
,'donuts'
,'dumplings'
,'edamame'
,'eggs_benedict'
,'escargots'
,'falafel'
,'filet_mignon'
,'fish_and_chips'
,'foie_gras'
,'french_fries'
,'french_onion_soup'
,'french_toast'
,'fried_calamari'
,'fried_rice'
,'frozen_yogurt'
,'galbijjim'
,'galchijorim'
,'ganjang_gejang'
,'garlic_bread'
,'gimbob'
,'gnocchi'
,'greek_salad'
,'grilled_cheese_sandwich'
,'grilled_salmon'
,'guacamole'
,'gyoza'
,'hamburger'
,'hot_and_sour_soup'
,'hot_dog'
,'huevos_rancheros'
,'hummus'
,'ice_cream'
,'jeyuk_bokkeum'
,'jjajangmyeon'
,'kimchi'
,'lasagna'
,'lobster_bisque'
,'lobster_roll_sandwich'
,'macaroni_and_cheese'
,'macarons'
,'miso_soup'
,'mussels'
,'nachos'
,'nangmyeon'
,'ojingeo_bokkeum'
,'omelette'
,'onion_rings'
,'oysters'
,'pad_thai'
,'paella'
,'pajeon'
,'pancakes'
,'panna_cotta'
,'peking_duck'
,'pho'
,'pizza'
,'pork_chop'
,'poutine'
,'prime_rib'
,'pulled_pork_sandwich'
,'ramen'
,'ravioli'
,'red_velvet_cake'
,'risotto'
,'samgupsal'
,'samgyetang'
,'samosa'
,'sashimi'
,'scallops'
,'seaweed_salad'
,'shrimp_and_grits'
,'soondae'
,'soondubu_jjigae'
,'spaghetti_bolognese'
,'spaghetti_carbonara'
,'spring_rolls'
,'steak'
,'strawberry_shortcake'
,'sushi'
,'tacos'
,'takoyaki'
,'tiramisu'
,'tuna_tartare'
,'waffles']

f = open('reslut.txt')
for line in f.readlines() :
    line = line.strip()
    x_y = line.split('\t')
    name = x_y[0].split('/')[-1][:-4]
    label = idx_to_name[int(x_y[1])-1]
    print '%s,%s'%(name,label)
#if __name__ == "__main__" :
#    f = open('super_category.prototxt')
#    flag = False
#    print len(idx_to_name)
#    for line in f.readlines() :
#        line = str.strip(line)
#        if( '#' in line ) :
#            label = str.strip(line.split('#')[1])
#            print idx_to_name.index(label)+1,',',
#        elif( '}' in line and flag) :
#            flag = False
#            print ''
#        elif('}' in line):
#            flag = True
#        else :
#            flag = False
#
